---
title: "Group Lab 2 - Mapping Data on Employment and Industry in the US"
author: "Group 4: Daniella, Emmi, Gabby, Macklan, Sean"
date: "January 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Context

<!-- EMMI: Discussion about errors in census data-->
<!-- Why our area is of particular interest-->
<!--Need to describe main findings when we're done with everything else.-->

#Non-Spatial Visualizations

```{r, include = FALSE}
# Second step
```

#Basic Static Maps

```{r, include = FALSE}
# Block level variable
library(sp)
library(ggplot2)
library(tmap)
library(tmaptools)
library(leaflet)
library(dplyr)
library(tigris)

library(tigris)
options(tigris_class = "sp")
co <- counties(cb = TRUE)
head(co)

library(RColorBrewer)
display.brewer.all(type="seq")
pal <- brewer.pal(9, "GnBu") 
class(pal)

#Tigris OK County Census Blocks 
OKC <- blocks(state = "40", county = "109")
print(OKC)

#All WAC data
WAC_all<- read.csv("/Users/gabbyshelley/Desktop/GIS directory/ok_wac_S000_JT00_2015.csv", stringsAsFactors = FALSE) 
print(WAC_all)

#Narrowing WAC data to only 40109 - Oklahoma County 
half<- filter(WAC_all, w_geocode > 401090000000000)
print(half)

full<- filter(half, w_geocode < 401100000000000)
print(full)

#Spatial Join
ok109_blocks <- geo_join(OKC, full, "GEOID10", "w_geocode")

#Oklahoma County Census Blocks looking at Total Jobs
spplot(ok109_blocks,"C000", col.regions = pal, cuts=8, main= "Total Number of Jobs within Oklahoma County Census Blocks") 
```

```{r, include = FALSE}
#Tract-level Variable 
library(sp)
library(ggplot2)
library(tmap)
library(tmaptools)
library(leaflet)
library(dplyr)

library(tigris)
options(tigris_class = "sp")
co <- counties(cb = TRUE)
head(co)

library(RColorBrewer)
display.brewer.all(type="seq")
pal <- brewer.pal(9, "GnBu") 
class(pal)

#Tigris Data for Oklahoma State Census Tracts
OK_tracts<- tracts('40', county = '109', cb = TRUE, year = 2015)
print(OK_tracts)


#Selecting Oklahoma County 
#wac_tract.csv is wac_okall_aggregation.csv 
WAC<- read.csv("/Users/gabbyshelley/Desktop/GIS directory/wac_tract.csv", stringsAsFactors = FALSE) 
#Selecting only OK County (109)
only109 <- WAC[c(422:662), c(1:53)]
print(only109)

#Spatial Join
ok109 <- geo_join(OK_tracts, only109, "GEOID", "work_tract")

#Static Map
spplot(ok109,"C000",col.regions = pal, cuts=8, main= "Total Number of Jobs within Oklahoma County Census Tracts") 
```



# Mapping OD Data

```{r, include = FALSE}
# Fourth and fifth step. Static or interactive map. Subset of a tract? Two layers
```

#Additional Analysis
```{r, include = FALSE}
# at least one additional geocomputation
```

